eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwwjava/springCLoudConfig
          username: 183078747@qq.com
          password: z4418613657.
management:
  endpoints:
    web:
      exposure:
        include: "*"