server:
  port: 9002
spring:
  application:
    name: server
eureka:
#  instance:
#    hostname: 101.132.168.231
#    instance-id: 192.168.99.100:${server.port}
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://101.132.168.231:9001/eureka/
  server:
    enable-self-preservation: false