server:
  port: 9001

spring:
  application:
    name: server

eureka:
#  instance:
#    hostname: localhost
#  client:
##    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:9002/eureka/
  server:
    enable-self-preservation: false