server:
  port: 9001

spring:
  application:
    name: server

eureka:
#  instance:
#    hostname: 192.168.99.100
#    instance-id: 192.168.99.100:${server.port}
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://192.168.99.100:9002/eureka/
  server:
    enable-self-preservation: false